apiVersion: blaxel.ai/v1alpha1
kind: IntegrationConnection
metadata:
  name: gemini-integration
spec:
  integration: gemini
  secret:
    apiKey: ${GEMINI_API_KEY}
---
apiVersion: blaxel.ai/v1alpha1
kind: Model
metadata:
  name: gemini-2-0-flash
  displayName: Gemini 2.0 Flash
spec:
  integrationConnections:
    - gemini-integration
  runtime:
    model: gemini-2.0-flash
    type: gemini
